create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  category text not null check (category in ('clothes', 'mens_clothing', 'womens_clothing', 'shoes', 'accessories')),
  description text not null default '' check (char_length(description) <= 1000),
  price_kes integer not null check (price_kes >= 0),
  stock integer not null default 0 check (stock >= 0),
  image_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  amount_kes integer not null check (amount_kes >= 0),
  phone text not null,
  checkout_request_id text unique,
  merchant_request_id text,
  status text not null default 'PENDING' check (status in ('PENDING', 'SUCCESS', 'FAILED')),
  result_description text,
  created_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products (category);
create index if not exists products_created_at_idx on public.products (created_at desc);
create index if not exists orders_product_id_idx on public.orders (product_id);
create index if not exists orders_status_idx on public.orders (status);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;
