create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('clothes', 'shoes', 'accessories')),
  description text default '',
  price_kes integer not null check (price_kes >= 0),
  stock integer not null default 0 check (stock >= 0),
  image_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  amount_kes integer,
  phone text,
  checkout_request_id text unique,
  merchant_request_id text,
  status text default 'PENDING',
  result_description text,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;
